In [1]:
import numpy as np
import gym
import random
import math

In [2]:
env = gym.make("slot_coating_env:slotdie-v0")

/opt/anaconda3/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [3]:
action_space_size = env.action_space.shape[0]
state_space_size = env.observation_space.shape[0]

In [4]:
action_space_size

3

In [5]:
state_space_size

2

In [6]:
# design algorithm for training
obs = env.reset()

for step in range(10000):
    action = env.action_space.sample()
    print(action)
    obs, reward, done, info = env.step(action)
    print(info)

[5.9636317e-02 4.8982816e+02 3.9131985e+00]
{'rewards': 63563.237751554596, 'done': False, 'observation': 3, 'total_rewards': 430213069.98937184}
[9.7875498e-02 2.1770740e+02 2.8573651e+00]
{'rewards': 20474.555437827796, 'done': False, 'observation': 3, 'total_rewards': 430233544.54480964}
[8.4917016e-02 4.2629016e+02 3.4187644e+00]
{'rewards': 68159.35942208402, 'done': False, 'observation': 3, 'total_rewards': 430301703.9042317}
[6.3098304e-02 4.2846426e+02 3.8230090e+00]
{'rewards': 51400.17948748374, 'done': False, 'observation': 3, 'total_rewards': 430353104.0837192}
[7.5090125e-02 3.0242621e+02 2.4572821e+00]
{'rewards': 30511.18297901761, 'done': False, 'observation': 3, 'total_rewards': 430383615.26669824}
[5.7744019e-02 3.6878003e+02 4.3057289e+00]
{'rewards': 34871.11575614398, 'done': False, 'observation': 3, 'total_rewards': 430418486.3824544}
[5.7873916e-02 3.0022479e+02 4.2783585e+00]
{'rewards': 23163.541095605997, 'done': False, 'observation': 3, 'total_rewards': 43044

[5.8786362e-02 4.2475922e+02 3.1173563e+00]
{'rewards': 47297.086775399, 'done': False, 'observation': 3, 'total_rewards': 443438943.7789768}
[7.3746964e-02 2.1413977e+02 2.7358625e+00]
{'rewards': 15009.75944370419, 'done': False, 'observation': 3, 'total_rewards': 443453953.5384205}
[8.0310427e-02 3.9605533e+02 3.0274167e+00]
{'rewards': 55751.15878339118, 'done': False, 'observation': 3, 'total_rewards': 443509704.6972039}
[7.3213592e-02 3.7817493e+02 2.5687418e+00]
{'rewards': 46521.340646992125, 'done': False, 'observation': 3, 'total_rewards': 443556226.03785086}
[7.3429443e-02 2.7399820e+02 3.5348568e+00]
{'rewards': 24402.044104740446, 'done': False, 'observation': 3, 'total_rewards': 443580628.0819556}
[7.8394324e-02 4.7504266e+02 1.8608943e+00]
{'rewards': 78814.37647359647, 'done': False, 'observation': 3, 'total_rewards': 443659442.4584292}
[7.3140442e-02 4.4668408e+02 4.0317583e+00]
{'rewards': 64526.5135056946, 'done': False, 'observation': 3, 'total_rewards': 443723968.9

[7.6749727e-02 3.8337601e+02 3.0869737e+00]
{'rewards': 49957.08964139409, 'done': False, 'observation': 3, 'total_rewards': 455341748.6084153}
[5.4035563e-02 4.1930139e+02 1.9350483e+00]
{'rewards': 43015.181037190516, 'done': False, 'observation': 3, 'total_rewards': 455384763.7894525}
[8.0128632e-02 4.8171414e+02 3.6404171e+00]
{'rewards': 82160.64293095053, 'done': False, 'observation': 3, 'total_rewards': 455466924.4323834}
[9.6135594e-02 3.3156403e+02 3.0771048e+00]
{'rewards': 46634.51691467663, 'done': False, 'observation': 3, 'total_rewards': 455513558.9492981}
[8.560733e-02 2.494954e+02 3.854179e+00]
{'rewards': 23514.406415045138, 'done': False, 'observation': 3, 'total_rewards': 455537073.3557131}
[7.8042403e-02 2.0484787e+02 4.6040220e+00]
{'rewards': 14451.044428816887, 'done': False, 'observation': 3, 'total_rewards': 455551524.40014195}
[9.4823569e-02 3.1841733e+02 2.6091766e+00]
{'rewards': 42481.101935764316, 'done': False, 'observation': 3, 'total_rewards': 455594005

[5.6544859e-02 3.5099005e+02 2.2533219e+00]
{'rewards': 31324.263606401695, 'done': False, 'observation': 3, 'total_rewards': 469882850.6920485}
[9.3267530e-02 3.4782358e+02 2.7178829e+00]
{'rewards': 49854.98848531684, 'done': False, 'observation': 3, 'total_rewards': 469932705.6805338}
[9.5286556e-02 4.9716367e+02 1.6508392e+00]
{'rewards': 104530.39841370682, 'done': False, 'observation': 3, 'total_rewards': 470037236.07894754}
[5.2348327e-02 2.2461044e+02 3.8583667e+00]
{'rewards': 11780.042167867141, 'done': False, 'observation': 3, 'total_rewards': 470049016.1211154}
[9.5001675e-02 2.6453754e+02 3.9112611e+00]
{'rewards': 29298.187314364102, 'done': False, 'observation': 3, 'total_rewards': 470078314.3084298}
[9.2157729e-02 4.8167987e+02 4.9012394e+00]
{'rewards': 94154.99042037842, 'done': False, 'observation': 3, 'total_rewards': 470172469.2988502}
[9.9112280e-02 4.5774771e+02 3.8031836e+00]
{'rewards': 91495.01409896214, 'done': False, 'observation': 3, 'total_rewards': 470263

{'rewards': 48269.715133983926, 'done': True, 'observation': 3, 'total_rewards': 484981546.26334214}
[9.4500951e-02 4.2452856e+02 2.4102690e+00]
{'rewards': 75308.6870971298, 'done': True, 'observation': 3, 'total_rewards': 485056854.9504393}
[6.0651705e-02 2.9727051e+02 4.5976415e+00]
{'rewards': 23753.456772886173, 'done': True, 'observation': 3, 'total_rewards': 485080608.40721214}
[5.217402e-02 4.419335e+02 4.245900e+00]
{'rewards': 45387.13146011063, 'done': True, 'observation': 3, 'total_rewards': 485125995.53867227}
[6.2114455e-02 4.0675705e+02 3.0863006e+00]
{'rewards': 45754.616342088, 'done': True, 'observation': 3, 'total_rewards': 485171750.15501434}
[7.7839345e-02 4.5262943e+02 3.2786398e+00]
{'rewards': 70564.35585889634, 'done': True, 'observation': 3, 'total_rewards': 485242314.51087326}
[7.2117299e-02 2.6630548e+02 4.3902407e+00]
{'rewards': 22602.774039177002, 'done': True, 'observation': 3, 'total_rewards': 485264917.2849124}
[6.0785018e-02 3.1048862e+02 1.5868181e+0

[7.0234880e-02 3.3583203e+02 2.3022277e+00]
{'rewards': 35293.56237346722, 'done': True, 'observation': 3, 'total_rewards': 500271072.24175715}
[6.6129193e-02 4.1718533e+02 4.2750087e+00]
{'rewards': 50955.98732563583, 'done': True, 'observation': 3, 'total_rewards': 500322028.22908276}
[8.6244076e-02 4.1958316e+02 1.8067194e+00]
{'rewards': 67481.9528729068, 'done': True, 'observation': 3, 'total_rewards': 500389510.1819557}
[8.4690660e-02 4.8195801e+02 3.9909093e+00]
{'rewards': 86800.75642492255, 'done': True, 'observation': 3, 'total_rewards': 500476310.9383806}
[8.2677692e-02 4.2066003e+02 3.0324621e+00]
{'rewards': 64712.02793370301, 'done': True, 'observation': 3, 'total_rewards': 500541022.9663143}
[6.9855399e-02 2.7928711e+02 4.1023817e+00]
{'rewards': 24107.78650339986, 'done': True, 'observation': 3, 'total_rewards': 500565130.7528177}
[9.0088062e-02 3.3269833e+02 4.2580051e+00]
{'rewards': 43949.44020423444, 'done': True, 'observation': 3, 'total_rewards': 500609080.1930219

{'rewards': 42872.065322700444, 'done': True, 'observation': 3, 'total_rewards': 513420484.09486914}
[5.9515223e-02 4.5795731e+02 4.7157736e+00]
{'rewards': 55325.746246610244, 'done': True, 'observation': 3, 'total_rewards': 513475809.8411158}
[6.1292466e-02 3.9507330e+02 1.7141294e+00]
{'rewards': 43147.814949847634, 'done': True, 'observation': 3, 'total_rewards': 513518957.65606564}
[9.9468939e-02 4.0437143e+02 4.4924626e+00]
{'rewards': 71601.2906610809, 'done': True, 'observation': 3, 'total_rewards': 513590558.94672674}
[9.7552061e-02 2.0091422e+02 2.3032649e+00]
{'rewards': 17409.25275779737, 'done': True, 'observation': 3, 'total_rewards': 513607968.1994845}
[5.5594586e-02 4.3794034e+02 1.7570623e+00]
{'rewards': 48340.45626124194, 'done': True, 'observation': 3, 'total_rewards': 513656308.65574574}
[5.4884851e-02 4.8929745e+02 3.4884329e+00]
{'rewards': 58621.1937449274, 'done': True, 'observation': 3, 'total_rewards': 513714929.84949064}
[6.0530707e-02 3.1276364e+02 3.667673

[9.7300574e-02 4.9488849e+02 4.2145820e+00]
{'rewards': 104956.8083998019, 'done': True, 'observation': 3, 'total_rewards': 527644351.4356267}
[6.3332275e-02 3.2124301e+02 2.5931349e+00]
{'rewards': 29162.685438874043, 'done': True, 'observation': 3, 'total_rewards': 527673514.12106556}
[5.6301963e-02 2.9429315e+02 2.0244687e+00]
{'rewards': 21994.575388813948, 'done': True, 'observation': 3, 'total_rewards': 527695508.69645435}
[7.2444074e-02 2.8517941e+02 2.9518523e+00]
{'rewards': 26137.626964584513, 'done': True, 'observation': 3, 'total_rewards': 527721646.3234189}
[6.4090274e-02 2.8103119e+02 1.8375471e+00]
{'rewards': 22735.547285718792, 'done': True, 'observation': 3, 'total_rewards': 527744381.87070465}
[6.6049010e-02 4.6379831e+02 2.9970775e+00]
{'rewards': 63169.15601848059, 'done': True, 'observation': 3, 'total_rewards': 527807551.02672315}
[9.4415948e-02 3.1660947e+02 2.0339441e+00]
{'rewards': 41916.11561151135, 'done': True, 'observation': 3, 'total_rewards': 527849467.

[9.3149997e-02 2.3860707e+02 4.4964838e+00]
{'rewards': 23359.47264665206, 'done': True, 'observation': 3, 'total_rewards': 542013853.5360833}
[8.4452085e-02 4.2505249e+02 2.0281878e+00]
{'rewards': 67748.11034447276, 'done': True, 'observation': 3, 'total_rewards': 542081601.6464279}
[6.6627763e-02 4.4583875e+02 2.3371921e+00]
{'rewards': 59097.722523950026, 'done': True, 'observation': 3, 'total_rewards': 542140699.3689518}
[5.0330859e-02 4.9186819e+02 4.2499366e+00]
{'rewards': 54300.26259019698, 'done': True, 'observation': 3, 'total_rewards': 542194999.631542}
[6.4657748e-02 3.6096002e+02 4.8679237e+00]
{'rewards': 37267.37742263665, 'done': True, 'observation': 3, 'total_rewards': 542232267.0089647}
[9.4172291e-02 3.8463782e+02 3.8403451e+00]
{'rewards': 61411.549492855076, 'done': True, 'observation': 3, 'total_rewards': 542293678.5584575}
[5.9724063e-02 3.7621646e+02 2.5289664e+00]
{'rewards': 37820.20911548705, 'done': True, 'observation': 3, 'total_rewards': 542331498.767573}

{'rewards': 20574.10588817793, 'done': True, 'observation': 3, 'total_rewards': 554861424.9943844}
[7.4659936e-02 4.8432474e+02 3.9835658e+00]
{'rewards': 77416.94480070192, 'done': True, 'observation': 3, 'total_rewards': 554938841.9391851}
[5.2022733e-02 3.0142651e+02 4.2972102e+00]
{'rewards': 21050.699945588713, 'done': True, 'observation': 3, 'total_rewards': 554959892.6391307}
[8.3883226e-02 2.3690477e+02 2.9867659e+00]
{'rewards': 20820.79253586036, 'done': True, 'observation': 3, 'total_rewards': 554980713.4316666}
[5.3904798e-02 3.2810275e+02 3.4457016e+00]
{'rewards': 25910.03547158928, 'done': True, 'observation': 3, 'total_rewards': 555006623.4671382}
[8.1246875e-02 4.7181491e+02 3.3356714e+00]
{'rewards': 79957.35562063538, 'done': True, 'observation': 3, 'total_rewards': 555086580.8227588}
[5.2481435e-02 3.7038434e+02 4.9546533e+00]
{'rewards': 31990.09102074364, 'done': True, 'observation': 3, 'total_rewards': 555118570.9137795}
[7.6739714e-02 3.5486145e+02 3.7477551e+00

{'rewards': 49507.6914819973, 'done': True, 'observation': 3, 'total_rewards': 568921161.622229}
[8.6844906e-02 3.9950314e+02 4.4304342e+00]
{'rewards': 61101.27504040897, 'done': True, 'observation': 3, 'total_rewards': 568982262.8972694}
[8.3720937e-02 2.1385788e+02 4.1161718e+00]
{'rewards': 16893.41552228707, 'done': True, 'observation': 3, 'total_rewards': 568999156.3127917}
[7.4504659e-02 4.7466159e+02 4.3615875e+00]
{'rewards': 74152.71534873453, 'done': True, 'observation': 3, 'total_rewards': 569073309.0281404}
[8.6475946e-02 4.1747070e+02 4.9878731e+00]
{'rewards': 66399.06192177317, 'done': True, 'observation': 3, 'total_rewards': 569139708.0900621}
[5.5223711e-02 4.2027344e+02 3.8396778e+00]
{'rewards': 43437.81314357934, 'done': True, 'observation': 3, 'total_rewards': 569183145.9032058}
[6.8370894e-02 2.8184836e+02 4.0066824e+00]
{'rewards': 24045.411816285705, 'done': True, 'observation': 3, 'total_rewards': 569207191.315022}
[7.8150682e-02 3.9976337e+02 1.8500496e+00]
{

{'rewards': 73679.07724312982, 'done': True, 'observation': 3, 'total_rewards': 580450653.9964567}
[7.5812452e-02 4.4069562e+02 2.9314649e+00]
{'rewards': 65258.5829395728, 'done': True, 'observation': 3, 'total_rewards': 580515912.5793964}
[9.7773097e-02 2.1875096e+02 2.9043660e+00]
{'rewards': 20647.71440661135, 'done': True, 'observation': 3, 'total_rewards': 580536560.293803}
[8.4848545e-02 2.8247287e+02 3.4062374e+00]
{'rewards': 29904.04381902976, 'done': True, 'observation': 3, 'total_rewards': 580566464.337622}
[9.2054054e-02 3.8359189e+02 4.1222992e+00]
{'rewards': 59695.911388369466, 'done': True, 'observation': 3, 'total_rewards': 580626160.2490104}
[6.7585073e-02 2.7377106e+02 1.7298664e+00]
{'rewards': 22728.190736091212, 'done': True, 'observation': 3, 'total_rewards': 580648888.4397465}
[7.6412000e-02 2.9402866e+02 3.1424377e+00]
{'rewards': 29252.84150367076, 'done': True, 'observation': 3, 'total_rewards': 580678141.2812501}
[7.0324324e-02 4.2003922e+02 2.3589060e+00]


[7.9139523e-02 2.7835236e+02 3.2367721e+00]
{'rewards': 27126.713644505624, 'done': True, 'observation': 3, 'total_rewards': 593661034.2792816}
[8.3481513e-02 3.3282687e+02 2.2755938e+00]
{'rewards': 41014.990635336166, 'done': True, 'observation': 3, 'total_rewards': 593702049.269917}
[6.9791876e-02 2.3289265e+02 3.3227212e+00]
{'rewards': 16784.79114576431, 'done': True, 'observation': 3, 'total_rewards': 593718834.0610628}
[8.9862622e-02 3.5446277e+02 3.5904167e+00]
{'rewards': 49814.176023372216, 'done': True, 'observation': 3, 'total_rewards': 593768648.2370862}
[6.5346584e-02 4.5325891e+02 2.8405166e+00]
{'rewards': 59754.30556971211, 'done': True, 'observation': 3, 'total_rewards': 593828402.542656}
[8.4484451e-02 3.8219254e+02 4.7014227e+00]
{'rewards': 54399.43680173608, 'done': True, 'observation': 3, 'total_rewards': 593882801.9794577}
[8.5828647e-02 3.8074039e+02 4.7763824e+00]
{'rewards': 54831.853178980404, 'done': True, 'observation': 3, 'total_rewards': 593937633.832636

{'rewards': 80570.23210060695, 'done': True, 'observation': 3, 'total_rewards': 607378043.5841851}
[8.7759875e-02 3.6018912e+02 3.9341719e+00]
{'rewards': 50219.15157010001, 'done': True, 'observation': 3, 'total_rewards': 607428262.7357552}
[5.0023422e-02 3.9284937e+02 1.9310923e+00]
{'rewards': 35143.27700902295, 'done': True, 'observation': 3, 'total_rewards': 607463406.0127642}
[9.0686403e-02 2.0331189e+02 3.5993524e+00]
{'rewards': 16536.163592153745, 'done': True, 'observation': 3, 'total_rewards': 607479942.1763563}
[7.0722483e-02 4.3175906e+02 1.7650895e+00]
{'rewards': 59011.55979031099, 'done': True, 'observation': 3, 'total_rewards': 607538953.7361466}
[9.5237434e-02 3.6770432e+02 3.7324364e+00]
{'rewards': 56759.9813076054, 'done': True, 'observation': 3, 'total_rewards': 607595713.7174542}
[6.9597766e-02 3.4539160e+02 2.0030079e+00]
{'rewards': 37094.289032349654, 'done': True, 'observation': 3, 'total_rewards': 607632808.0064865}
[7.7495158e-02 4.7412564e+02 4.2715578e+00

[8.8443436e-02 3.7972385e+02 2.2572980e+00]
{'rewards': 56494.63623345089, 'done': True, 'observation': 3, 'total_rewards': 620372505.450882}
[6.9024310e-02 3.7016458e+02 2.9495723e+00]
{'rewards': 42009.4885465905, 'done': True, 'observation': 3, 'total_rewards': 620414514.9394286}
[8.1388280e-02 2.3807681e+02 3.6135762e+00]
{'rewards': 20379.928728790484, 'done': True, 'observation': 3, 'total_rewards': 620434894.8681574}
[9.2954367e-02 4.7432922e+02 2.3888087e+00]
{'rewards': 92509.02351271333, 'done': True, 'observation': 3, 'total_rewards': 620527403.8916701}
[7.664067e-02 3.973363e+02 3.294550e+00]
{'rewards': 53552.68527504636, 'done': True, 'observation': 3, 'total_rewards': 620580956.5769452}
[9.2665091e-02 4.2649808e+02 3.1694055e+00]
{'rewards': 74398.96394894912, 'done': True, 'observation': 3, 'total_rewards': 620655355.5408942}
[6.3372470e-02 3.3855499e+02 2.3991315e+00]
{'rewards': 32456.39800919637, 'done': True, 'observation': 3, 'total_rewards': 620687811.9389033}
[9.

[6.0074612e-02 2.9737717e+02 2.4470537e+00]
{'rewards': 23778.79338157942, 'done': True, 'observation': 3, 'total_rewards': 628046453.8119287}
[8.7824754e-02 2.2077414e+02 3.7551932e+00]
{'rewards': 18885.989306970914, 'done': True, 'observation': 3, 'total_rewards': 628065339.8012357}
[8.1471205e-02 2.6060617e+02 2.8621993e+00]
{'rewards': 24493.61716583781, 'done': True, 'observation': 3, 'total_rewards': 628089833.4184015}
[5.3024653e-02 4.8934497e+02 4.1113758e+00]
{'rewards': 56555.53253840064, 'done': True, 'observation': 3, 'total_rewards': 628146388.9509399}
[8.1342973e-02 3.5348599e+02 1.9817021e+00]
{'rewards': 45188.871845307374, 'done': True, 'observation': 3, 'total_rewards': 628191577.8227853}
[7.504165e-02 4.945321e+02 3.837928e+00]
{'rewards': 81145.76686114894, 'done': True, 'observation': 3, 'total_rewards': 628272723.5896465}
[8.4171943e-02 2.9356723e+02 1.7417328e+00]
{'rewards': 32279.610497468715, 'done': True, 'observation': 3, 'total_rewards': 628305003.2001439}

[5.151425e-02 3.943104e+02 4.192817e+00]
{'rewards': 35696.955355565704, 'done': True, 'observation': 3, 'total_rewards': 638629811.7764239}
[5.3535074e-02 2.5627222e+02 3.1182904e+00]
{'rewards': 15732.842130220453, 'done': True, 'observation': 3, 'total_rewards': 638645544.6185541}
[8.5026726e-02 4.4478772e+02 2.8896315e+00]
{'rewards': 74398.91721308058, 'done': True, 'observation': 3, 'total_rewards': 638719943.5357672}
[5.3390380e-02 3.6898444e+02 3.7830732e+00]
{'rewards': 32414.166851103357, 'done': True, 'observation': 3, 'total_rewards': 638752357.7026184}
[9.172305e-02 3.158968e+02 2.291866e+00]
{'rewards': 40512.88063384935, 'done': True, 'observation': 3, 'total_rewards': 638792870.5832522}
[6.0434029e-02 4.2558145e+02 4.4307218e+00]
{'rewards': 48534.43340188887, 'done': True, 'observation': 3, 'total_rewards': 638841405.0166541}
[7.1678266e-02 3.9825525e+02 4.9344811e+00]
{'rewards': 50203.19064030696, 'done': True, 'observation': 3, 'total_rewards': 638891608.2072945}
[6

[8.3727166e-02 2.2311409e+02 4.9590163e+00]
{'rewards': 18368.65191971221, 'done': True, 'observation': 3, 'total_rewards': 649447909.9613967}
[7.7508152e-02 3.8915356e+02 2.5397825e+00]
{'rewards': 52083.74181644453, 'done': True, 'observation': 3, 'total_rewards': 649499993.7032131}
[5.2254647e-02 2.9742841e+02 4.4009738e+00]
{'rewards': 20576.876088260735, 'done': True, 'observation': 3, 'total_rewards': 649520570.5793014}
[9.7514682e-02 2.1201324e+02 3.6527426e+00]
{'rewards': 19318.15993926617, 'done': True, 'observation': 3, 'total_rewards': 649539888.7392406}
[8.8221498e-02 4.8864938e+02 4.1344709e+00]
{'rewards': 92881.72229306273, 'done': True, 'observation': 3, 'total_rewards': 649632770.4615337}
[7.9971142e-02 3.6444690e+02 2.8583174e+00]
{'rewards': 47038.13823090426, 'done': True, 'observation': 3, 'total_rewards': 649679808.5997646}
[8.330103e-02 2.714859e+02 2.830934e+00]
{'rewards': 27169.86239314536, 'done': True, 'observation': 3, 'total_rewards': 649706978.4621577}
[

[9.7649843e-02 4.8693338e+02 3.7218087e+00]
{'rewards': 102033.27158515225, 'done': True, 'observation': 3, 'total_rewards': 661310012.0954728}
[7.3624276e-02 3.1611215e+02 3.9257329e+00]
{'rewards': 32533.292714580577, 'done': True, 'observation': 3, 'total_rewards': 661342545.3881874}
[7.6108105e-02 4.7470831e+02 4.0700088e+00]
{'rewards': 75779.2594725653, 'done': True, 'observation': 3, 'total_rewards': 661418324.64766}
[9.3062587e-02 2.7705096e+02 4.2422504e+00]
{'rewards': 31473.08275626097, 'done': True, 'observation': 3, 'total_rewards': 661449797.7304163}
[5.2475479e-02 4.4961798e+02 3.5700021e+00]
{'rewards': 47382.27038432821, 'done': True, 'observation': 3, 'total_rewards': 661497180.0008006}
[7.4764378e-02 2.1357748e+02 1.6057400e+00]
{'rewards': 15259.875412116404, 'done': True, 'observation': 3, 'total_rewards': 661512439.8762127}
[5.3228762e-02 4.2549579e+02 4.1523566e+00]
{'rewards': 42912.22817575487, 'done': True, 'observation': 3, 'total_rewards': 661555352.1043885}

[9.1052763e-02 3.6690433e+02 2.0651486e+00]
{'rewards': 54318.34640030361, 'done': True, 'observation': 3, 'total_rewards': 671456176.3167229}
[8.0365665e-02 2.1613583e+02 3.6294744e+00]
{'rewards': 16588.173085543553, 'done': True, 'observation': 3, 'total_rewards': 671472764.4898084}
[6.8125047e-02 2.6727838e+02 2.9522300e+00]
{'rewards': 21623.67599004937, 'done': True, 'observation': 3, 'total_rewards': 671494388.1657985}
[8.7301388e-02 3.2337430e+02 2.5821664e+00]
{'rewards': 40399.04861854973, 'done': True, 'observation': 3, 'total_rewards': 671534787.2144171}
[7.1179517e-02 4.0367935e+02 4.1570215e+00]
{'rewards': 51297.25530241666, 'done': True, 'observation': 3, 'total_rewards': 671586084.4697195}
[5.6184191e-02 3.4382880e+02 2.4419756e+00]
{'rewards': 29818.251570144694, 'done': True, 'observation': 3, 'total_rewards': 671615902.7212896}
[8.6206824e-02 3.2948270e+02 3.4091775e+00]
{'rewards': 41327.27691165392, 'done': True, 'observation': 3, 'total_rewards': 671657229.998201

[7.0789829e-02 4.4961053e+02 2.4637718e+00]
{'rewards': 63677.349996731646, 'done': True, 'observation': 3, 'total_rewards': 684807154.5213321}
[9.7850457e-02 2.4108078e+02 4.5314789e+00]
{'rewards': 25037.78961243123, 'done': True, 'observation': 3, 'total_rewards': 684832192.3109446}
[7.6650992e-02 4.6139810e+02 3.3763874e+00]
{'rewards': 72206.33308859148, 'done': True, 'observation': 3, 'total_rewards': 684904398.6440332}
[9.6184604e-02 3.8465613e+02 3.7872906e+00]
{'rewards': 62720.353611973536, 'done': True, 'observation': 3, 'total_rewards': 684967118.9976451}
[6.2864400e-02 4.5415417e+02 3.2064316e+00]
{'rewards': 57674.39113325423, 'done': True, 'observation': 3, 'total_rewards': 685024793.3887784}
[8.6181447e-02 3.1979852e+02 3.1069627e+00]
{'rewards': 38949.8940012548, 'done': True, 'observation': 3, 'total_rewards': 685063743.2827797}
[8.8611066e-02 3.3689856e+02 3.0376871e+00]
{'rewards': 44433.917220533665, 'done': True, 'observation': 3, 'total_rewards': 685108177.200000

[6.3257247e-02 3.5105286e+02 3.2113731e+00]
{'rewards': 34668.57119225948, 'done': True, 'observation': 3, 'total_rewards': 697283608.514152}
[9.7945385e-02 2.8493997e+02 2.6570499e+00]
{'rewards': 35115.976550683874, 'done': True, 'observation': 3, 'total_rewards': 697318724.4907027}
[6.3292325e-02 4.8807669e+02 3.3481519e+00]
{'rewards': 67012.09672887143, 'done': True, 'observation': 3, 'total_rewards': 697385736.5874317}
[7.7769428e-02 4.1786621e+02 2.7816737e+00]
{'rewards': 60188.06391477039, 'done': True, 'observation': 3, 'total_rewards': 697445924.6513464}
[5.5085111e-02 3.3476663e+02 3.6211565e+00]
{'rewards': 27519.31304267737, 'done': True, 'observation': 3, 'total_rewards': 697473443.9643891}
[8.6546525e-02 3.0277048e+02 3.2733529e+00]
{'rewards': 35043.805502666255, 'done': True, 'observation': 3, 'total_rewards': 697508487.7698917}
[8.8031389e-02 3.6612689e+02 4.4418354e+00]
{'rewards': 52010.98982980236, 'done': True, 'observation': 3, 'total_rewards': 697560498.7597215

[6.4063407e-02 2.3050938e+02 4.6957183e+00]
{'rewards': 15065.496343825283, 'done': True, 'observation': 3, 'total_rewards': 711257298.6936578}
[9.5361724e-02 2.6636581e+02 3.7338252e+00]
{'rewards': 29823.376455016692, 'done': True, 'observation': 3, 'total_rewards': 711287122.0701128}
[9.6558914e-02 4.5061209e+02 2.9020462e+00]
{'rewards': 86543.26833272785, 'done': True, 'observation': 3, 'total_rewards': 711373665.3384455}
[6.7744099e-02 4.6385641e+02 4.4139957e+00]
{'rewards': 64484.50616763958, 'done': True, 'observation': 3, 'total_rewards': 711438149.8446132}
[7.3990591e-02 3.0803384e+02 2.8869059e+00]
{'rewards': 31138.707999324615, 'done': True, 'observation': 3, 'total_rewards': 711469288.5526125}
[7.9730555e-02 4.1463934e+02 3.4425516e+00]
{'rewards': 60603.06266952514, 'done': True, 'observation': 3, 'total_rewards': 711529891.615282}
[9.0340026e-02 4.6138416e+02 4.1742649e+00]
{'rewards': 84767.29542631778, 'done': True, 'observation': 3, 'total_rewards': 711614658.910708

[8.3528943e-02 2.2230147e+02 2.5982859e+00]
{'rewards': 18281.08277363233, 'done': True, 'observation': 3, 'total_rewards': 721730277.4069673}
[5.1302411e-02 2.5478868e+02 3.6803930e+00]
{'rewards': 14878.962506133124, 'done': True, 'observation': 3, 'total_rewards': 721745156.3694735}
[9.4268918e-02 4.4424426e+02 1.8502789e+00]
{'rewards': 82480.99148563799, 'done': True, 'observation': 3, 'total_rewards': 721827637.360959}
[7.5967543e-02 2.7673053e+02 4.1581011e+00]
{'rewards': 25700.32760102697, 'done': True, 'observation': 3, 'total_rewards': 721853337.6885601}
[7.8707717e-02 4.1612143e+02 2.8275867e+00]
{'rewards': 60380.55309172175, 'done': True, 'observation': 3, 'total_rewards': 721913718.2416519}
[9.4181910e-02 3.3538055e+02 4.9441638e+00]
{'rewards': 46637.475662655794, 'done': True, 'observation': 3, 'total_rewards': 721960355.7173146}
[7.9287209e-02 2.5941257e+02 4.4544487e+00]
{'rewards': 23545.23784274427, 'done': True, 'observation': 3, 'total_rewards': 721983900.9551574

[9.9649526e-02 3.2717148e+02 4.3722229e+00]
{'rewards': 46961.18977626228, 'done': True, 'observation': 3, 'total_rewards': 734828424.3151768}
[8.6320072e-02 3.9214047e+02 4.9766550e+00]
{'rewards': 58481.88768023249, 'done': True, 'observation': 3, 'total_rewards': 734886906.202857}
[8.9367762e-02 2.5069164e+02 3.1840670e+00]
{'rewards': 24801.42038507146, 'done': True, 'observation': 3, 'total_rewards': 734911707.6232421}
[5.5899579e-02 4.0128851e+02 1.7948059e+00]
{'rewards': 40767.57071228765, 'done': True, 'observation': 3, 'total_rewards': 734952475.1939545}
[5.3348318e-02 4.9193246e+02 1.7167565e+00]
{'rewards': 58745.74199187534, 'done': True, 'observation': 3, 'total_rewards': 735011220.9359463}
[5.8782343e-02 2.3803619e+02 2.3718133e+00]
{'rewards': 14931.543965592957, 'done': True, 'observation': 3, 'total_rewards': 735026152.4799119}
[6.6599540e-02 4.9434491e+02 3.1283913e+00]
{'rewards': 72303.83299046863, 'done': True, 'observation': 3, 'total_rewards': 735098456.3129025}

{'rewards': 47541.132333259055, 'done': True, 'observation': 3, 'total_rewards': 747645908.8221436}
[9.6801825e-02 3.0054028e+02 2.8853102e+00]
{'rewards': 38594.28158014391, 'done': True, 'observation': 3, 'total_rewards': 747684503.1037236}
[6.826398e-02 4.088917e+02 4.133090e+00]
{'rewards': 50515.88182103226, 'done': True, 'observation': 3, 'total_rewards': 747735018.9855447}
[7.0187770e-02 4.9991531e+02 3.2233284e+00]
{'rewards': 77796.8056438315, 'done': True, 'observation': 3, 'total_rewards': 747812815.7911885}
[8.0217570e-02 3.9999625e+02 2.4338505e+00]
{'rewards': 56932.560759699336, 'done': True, 'observation': 3, 'total_rewards': 747869748.3519481}
[7.0299789e-02 2.1352063e+02 3.4547389e+00]
{'rewards': 14202.801869561257, 'done': True, 'observation': 3, 'total_rewards': 747883951.1538177}
[5.8924615e-02 2.3289816e+02 2.5556216e+00]
{'rewards': 14304.211107289706, 'done': True, 'observation': 3, 'total_rewards': 747898255.3649249}
[7.0992030e-02 4.6643237e+02 3.7879448e+00]

[6.7792095e-02 4.8278455e+02 4.7122765e+00]
{'rewards': 69863.03942837156, 'done': True, 'observation': 3, 'total_rewards': 762834763.7546996}
[6.9108650e-02 2.5305153e+02 1.7727894e+00]
{'rewards': 19825.45547259226, 'done': True, 'observation': 3, 'total_rewards': 762854589.2101722}
[7.3940620e-02 3.0553436e+02 4.2326703e+00]
{'rewards': 30501.681760471187, 'done': True, 'observation': 3, 'total_rewards': 762885090.8919326}
[9.6881032e-02 4.0400504e+02 4.5811439e+00]
{'rewards': 69621.7496198591, 'done': True, 'observation': 3, 'total_rewards': 762954712.6415524}
[6.2521003e-02 2.9628284e+02 2.1196082e+00]
{'rewards': 24598.787043690612, 'done': True, 'observation': 3, 'total_rewards': 762979311.4285961}
[8.5618950e-02 3.0303851e+02 1.8042128e+00]
{'rewards': 34952.689576834535, 'done': True, 'observation': 3, 'total_rewards': 763014264.118173}
[5.6008849e-02 2.3505989e+02 1.6190299e+00]
{'rewards': 14062.023164648022, 'done': True, 'observation': 3, 'total_rewards': 763028326.141337

[8.2782052e-02 2.2145119e+02 4.5902524e+00]
{'rewards': 17901.64383586349, 'done': True, 'observation': 3, 'total_rewards': 776992204.0848325}
[7.0873030e-02 3.2570712e+02 4.6201000e+00]
{'rewards': 33223.43113366776, 'done': True, 'observation': 3, 'total_rewards': 777025427.5159662}
[9.3847893e-02 4.7708743e+02 3.9911005e+00]
{'rewards': 94139.54019546106, 'done': True, 'observation': 3, 'total_rewards': 777119567.0561616}
[5.9287712e-02 2.1615236e+02 1.5216646e+00]
{'rewards': 12564.556532938732, 'done': True, 'observation': 3, 'total_rewards': 777132131.6126946}
[5.9107918e-02 3.0706393e+02 4.6691484e+00]
{'rewards': 24709.05594978292, 'done': True, 'observation': 3, 'total_rewards': 777156840.6686444}
[8.4749840e-02 3.8738943e+02 2.3346252e+00]
{'rewards': 56374.00276713247, 'done': True, 'observation': 3, 'total_rewards': 777213214.6714115}
[8.3440527e-02 2.2796764e+02 2.9351006e+00]
{'rewards': 19182.510759363988, 'done': True, 'observation': 3, 'total_rewards': 777232397.182170

{'rewards': 49834.23653117565, 'done': True, 'observation': 3, 'total_rewards': 791140187.9433745}
[8.6446516e-02 4.5530020e+02 2.8014243e+00]
{'rewards': 79257.669010843, 'done': True, 'observation': 3, 'total_rewards': 791219445.6123854}
[9.4053507e-02 4.8319989e+02 1.6023071e+00]
{'rewards': 97531.68818024774, 'done': True, 'observation': 3, 'total_rewards': 791316977.3005656}
[5.8995858e-02 4.6923004e+02 3.3518603e+00]
{'rewards': 57849.93155810343, 'done': True, 'observation': 3, 'total_rewards': 791374827.2321237}
[5.9906691e-02 3.9790244e+02 4.9640021e+00]
{'rewards': 42012.24293182202, 'done': True, 'observation': 3, 'total_rewards': 791416839.4750556}
[5.5172872e-02 4.8794403e+02 2.2822006e+00]
{'rewards': 59124.96914997723, 'done': True, 'observation': 3, 'total_rewards': 791475964.4442055}
[7.8805603e-02 3.8606195e+02 4.9479856e+00]
{'rewards': 51801.414358497655, 'done': True, 'observation': 3, 'total_rewards': 791527765.858564}
[9.2995018e-02 4.0450818e+02 3.0886393e+00]
{

[5.7878532e-02 3.6016730e+02 1.6849068e+00]
{'rewards': 33996.19637834652, 'done': True, 'observation': 3, 'total_rewards': 806227322.1668003}
[8.8213004e-02 2.9480530e+02 2.4595618e+00]
{'rewards': 33935.66897852021, 'done': True, 'observation': 3, 'total_rewards': 806261257.8357788}
[6.0006723e-02 4.0296689e+02 3.1384113e+00]
{'rewards': 43417.71770397454, 'done': True, 'observation': 3, 'total_rewards': 806304675.5534828}
[5.9427086e-02 3.0964182e+02 3.5177279e+00]
{'rewards': 25350.730058714653, 'done': True, 'observation': 3, 'total_rewards': 806330026.2835414}
[8.7987766e-02 2.1236974e+02 4.3273640e+00]
{'rewards': 17492.643859213018, 'done': True, 'observation': 3, 'total_rewards': 806347518.9274007}
[9.5088877e-02 2.9151865e+02 1.8829639e+00]
{'rewards': 35812.59204598609, 'done': True, 'observation': 3, 'total_rewards': 806383331.5194467}
[5.5100303e-02 4.6884781e+02 3.5545471e+00]
{'rewards': 54010.13568759866, 'done': True, 'observation': 3, 'total_rewards': 806437341.655134

[5.3573452e-02 4.5541028e+02 2.7454481e+00]
{'rewards': 49856.13077762009, 'done': True, 'observation': 3, 'total_rewards': 821395841.2403715}
[7.7242970e-02 4.5663733e+02 4.5964079e+00]
{'rewards': 71086.91185132247, 'done': True, 'observation': 3, 'total_rewards': 821466928.1522228}
[7.7422410e-02 3.2367288e+02 3.7342637e+00]
{'rewards': 35852.656227454594, 'done': True, 'observation': 3, 'total_rewards': 821502780.8084502}
[7.0308730e-02 4.7496185e+02 3.0271568e+00]
{'rewards': 70394.82014413623, 'done': True, 'observation': 3, 'total_rewards': 821573175.6285944}
[9.8332211e-02 2.2779794e+02 3.4450421e+00]
{'rewards': 22493.97379694491, 'done': True, 'observation': 3, 'total_rewards': 821595669.6023914}
[5.6302104e-02 3.2533160e+02 2.4690700e+00]
{'rewards': 26742.71197594837, 'done': True, 'observation': 3, 'total_rewards': 821622412.3143673}
[9.667092e-02 4.799017e+02 2.637260e+00]
{'rewards': 98339.01973102448, 'done': True, 'observation': 3, 'total_rewards': 821720751.3340983}
[

[9.145351e-02 4.652764e+02 4.564143e+00]
{'rewards': 87215.06331023497, 'done': True, 'observation': 3, 'total_rewards': 836145898.6282066}
[8.8273562e-02 2.2049529e+02 3.6198635e+00]
{'rewards': 18937.853501756414, 'done': True, 'observation': 3, 'total_rewards': 836164836.4817084}
[6.4733341e-02 2.4882312e+02 4.0601397e+00]
{'rewards': 17760.812292376588, 'done': True, 'observation': 3, 'total_rewards': 836182597.2940007}
[5.0445620e-02 4.8133716e+02 4.6835799e+00]
{'rewards': 52032.87370237691, 'done': True, 'observation': 3, 'total_rewards': 836234630.1677032}
[9.3201332e-02 2.3827487e+02 2.4054868e+00]
{'rewards': 23403.466372557596, 'done': True, 'observation': 3, 'total_rewards': 836258033.6340758}
[5.4823883e-02 2.1384003e+02 2.8021917e+00]
{'rewards': 11231.850569367329, 'done': True, 'observation': 3, 'total_rewards': 836269265.4846451}
[8.3061799e-02 4.4730338e+02 4.6188350e+00]
{'rewards': 73280.39219733738, 'done': True, 'observation': 3, 'total_rewards': 836342545.8768425

[5.7640567e-02 4.0917892e+02 3.1377108e+00]
{'rewards': 43059.72251537774, 'done': True, 'observation': 3, 'total_rewards': 849661111.453968}
[7.8540422e-02 4.8124210e+02 3.9649367e+00]
{'rewards': 80346.11627105359, 'done': True, 'observation': 3, 'total_rewards': 849741457.5702391}
[9.2105694e-02 3.2689081e+02 2.6915619e+00]
{'rewards': 43498.17485862549, 'done': True, 'observation': 3, 'total_rewards': 849784955.7450976}
[5.3215764e-02 3.0699536e+02 1.5890316e+00]
{'rewards': 22893.09086224843, 'done': True, 'observation': 3, 'total_rewards': 849807848.8359599}
[8.4530808e-02 4.9656363e+02 3.4396405e+00]
{'rewards': 92065.34800156312, 'done': True, 'observation': 3, 'total_rewards': 849899914.1839615}
[6.3619249e-02 4.8668643e+02 2.1046815e+00]
{'rewards': 67500.51655869056, 'done': True, 'observation': 3, 'total_rewards': 849967414.7005202}
[8.1532292e-02 4.3306943e+02 2.0959232e+00]
{'rewards': 67929.13485177307, 'done': True, 'observation': 3, 'total_rewards': 850035343.835372}
[

[5.6203995e-02 3.3671469e+02 3.6714275e+00]
{'rewards': 28381.263795547926, 'done': True, 'observation': 3, 'total_rewards': 865938034.8109387}
[9.0481944e-02 3.6098239e+02 3.8357005e+00]
{'rewards': 51994.12843081, 'done': True, 'observation': 3, 'total_rewards': 865990028.9393696}
[7.2948270e-02 4.7588733e+02 3.5897584e+00]
{'rewards': 73127.84178032691, 'done': True, 'observation': 3, 'total_rewards': 866063156.7811499}
[5.8869518e-02 3.3116409e+02 3.9302907e+00]
{'rewards': 28688.007661342748, 'done': True, 'observation': 3, 'total_rewards': 866091844.7888112}
[7.8691527e-02 4.1478723e+02 3.2397676e+00]
{'rewards': 59901.72646741432, 'done': True, 'observation': 3, 'total_rewards': 866151746.5152786}
[5.3053472e-02 2.9253519e+02 2.5938590e+00]
{'rewards': 20408.79246468612, 'done': True, 'observation': 3, 'total_rewards': 866172155.3077433}
[9.2770949e-02 2.3638699e+02 2.4578407e+00]
{'rewards': 22925.230226140204, 'done': True, 'observation': 3, 'total_rewards': 866195080.5379695}

In [5]:
[info]

[{'rewards': 56574.29967628406,
  'done': True,
  'observation': 3,
  'total_rewards': 430149506.7516203}]

In [5]:
reward

21112.62640634411